### ISSUE TITLE
Endgame bugs

### ISSUE THREAD

**Issue by jacob-sahl** [jacob-sahl/red-herring#38]
- Background music ends sometimes, doesn’t loop I think.
- When you run out of time and fade into the end screen, the timer displays as -01:-01
- When the game ends and is reset, music doesn’t restart, and can no longer interact with the typewriter (most urgent)
- When restarting a game, the end screen text persists from the previous game along with the new text
- Ending screen formatting has an extra period

**Comment by 12Metatron** [comment]
![image](https://user-images.githubusercontent.com/44102139/196214202-7fd5bffc-bcb1-4780-823e-cfc2ce9c863c.png)
do this on audiomanager object in mainscene to fix audio looping issue
